get:
  x-eov-operation-id: getMultiUserOAuthCredentials
  x-eov-operation-handler: v1/handlers/credentials/credentials.handler
  tags:
    - Credential
  summary: Retrieve OAuth multi-user enabled credentials
  description: Retrieve all OAuth credentials that have useUserFilter enabled for multi-user workflows
  parameters:
    - $ref: '../../../../shared/spec/parameters/limit.yml'
    - $ref: '../../../../shared/spec/parameters/cursor.yml'
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../schemas/credential.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
    '403':
      $ref: '../../../../shared/spec/responses/forbidden.yml'
